CREATE TABLE IF NOT EXISTS b_xmldoc_log (
    ID int NOT NULL AUTO_INCREMENT,
    ENTITY_TYPE varchar(32) NOT NULL,
    ENTITY_ID int NOT NULL,
    STATUS varchar(32) NOT NULL,
    MESSAGE text,
    CREATED_AT datetime NOT NULL,
    PRIMARY KEY (ID),
    KEY IX_XMLDOC_ENTITY (ENTITY_TYPE, ENTITY_ID),
    KEY IX_XMLDOC_CREATED (CREATED_AT)
);

CREATE TABLE IF NOT EXISTS b_xmldoc_document (
    ID int NOT NULL AUTO_INCREMENT,
    ENTITY_TYPE varchar(32) NOT NULL,
    ENTITY_ID int NOT NULL,
    DOC_NUMBER varchar(64) DEFAULT NULL,
    FILE_NAME varchar(255) NOT NULL,
    FILE_ID int DEFAULT NULL,
    VERSION int NOT NULL DEFAULT 1,
    ENCODING varchar(16) DEFAULT 'windows-1251',
    FILE_HASH varchar(64) DEFAULT NULL,
    DOC_STATUS varchar(32) NOT NULL DEFAULT 'generated',
    XML_FORMAT_VERSION varchar(8) DEFAULT '5.03',
    CREATED_AT datetime NOT NULL,
    PRIMARY KEY (ID),
    KEY IX_XMLDOC_DOC_ENTITY (ENTITY_TYPE, ENTITY_ID),
    KEY IX_XMLDOC_DOC_VERSION (ENTITY_TYPE, ENTITY_ID, VERSION)
);
